### ISSUE TITLE
Publish all built Docker artifacts

### ISSUE THREAD

**Issue by ticean** [reactioncommerce/base#15]
The Reaction CI workflow now publishes all build Docker image to Docker Hub. Please update this repo to do the same.

We've been working on an [internal project template](https://github.com/reactioncommerce/generator-reaction-next/blob/master/generators/circleci/templates/circleci/config-workflow-docker.yml) that has an example of this.

* All Docker images from this repo build should be published to Hub.
* CI from forks must not publish to Hub.
* Images should be tagged with git sha1, git branch, git tags (if applicable), and `latest` if it is the highest tagged version on master. (We already have a script that will calculate the Docker tags.)

**Comment by impactmass** [comment]
@ticean for this requirement "CI from forks must not publish to Hub", do we have it disabled from Circle's admin panel?

With this test PR #19, I see that the CI steps are frozen (or not triggered). It seems that's in place

**Comment by ticean** [comment]
Regarding CI for forks. Spencer had reported that the Reaction project was attempting to push to Docker and failing. We just need to make sure that doesn't happen here.

In your forked test, I see a green check on the commit, but I don't see test results at the bottom of the pull request. Did tests run? Am I'm missing something?

We don't want to globally disable tests on forks, only the Docker publish workflow job. There are [CIrcleCI ENV variables](https://circleci.com/docs/2.0/env-vars/) that are set on forked builds. We could test those in the publish test and only execute the publish if it's a build from our repo, and run other jobs as usual.

**Comment by impactmass** [comment]
> In the forked test, the tests (and other CI jobs) did not run. It wasn't showing at the time you checked because I closed the PR by then (I've re-opened).
The green check was only for the WIP integration.
Using the CircleCI's ENV vars is good, but I was trying to confirm why they weren't running.

Putting this here for reference. The settings in CircleCI are now updated to build for forks. I'll add the check to use Circle ENV to not publish it.
