### ISSUE TITLE
The latest v4.0.1 can not build a reaction docker image in reaction v1.8.2

### ISSUE THREAD

**Issue by AllenBird** [reactioncommerce/base#22]
I glad to found base could be install the whole meteor. I had do this before, beacuse it will save a lot time when build app docker image.
But, it may have some problem with v4.0.1,  when I use it to build reaction v1.8.2

**Comment by ticean** [comment]
Hi @AllenBird. thanks for letting us know. Could you provide logs that describe problem you're having? I'm not sure if this affects you but we've moved functionality that was formerly in `docker-compose.yml` to `docker-compose-demo.yml`. That won't be a factor if you're building directly in Docker.

**Comment by AllenBird** [comment]
Thinks for @ticean reply~
first, I pull a image form docker
`reactioncommerce/base            latest              5b078589b45e        10 days ago         1.42GB`

then, I build a docker image in a reaction project root path.
`BIGAPP-frontedgedeMacBook-Air:reaction bigapp_frontedge$ pwd
/Users/bigapp_frontedge/reaction`
`docker build -t reactioncommerce/reaction:latest .`

next, I run the `reactioncommerce/reaction:latest` image. but it's not work.
`bc5b33ae9e33        reactioncommerce/reaction:latest   "node"              20 seconds ago      Exited (0) 18 seconds ago                       reaction
docker logs bc5b33ae9e33
`
there have no print logs.

I did't find a file called `docker-compose-demo.yml` in  reaction v1.8.2
Am I missing something?

**Comment by AllenBird** [comment]
Hi, @ticean 
I found reaction v1.9.0 is change its Dockerfile.
It should be used in v1.9.0 above, but it not tagged, so I did't find before.

**Comment by impactmass** [comment]
Hi @AllenBird, thanks for sharing the specific steps you walked through.

I believe the problem you had would have been prevented by using the specific reactioncommerce/base version in the Dockerfile that came with the version of Reaction you're using. Changing to `:latest` means that you might get a newer release that may need you to update your Reaction Dockerfile.

That is what you alluded to in your last comment (Reaction v1.9.0 has an updated Dockerfile to use v4.0.1).

So, if you are using Reaction v1.8.0, keep the reactioncommerce/base version as specified (v3.0.0), and your build should work fine.

I hope this helps. Do post a response if this is still an issue.

(PS: You can also check the changes in v4 on the release [notes](https://github.com/reactioncommerce/base/releases/tag/v4.0.0)).

**Comment by ticean** [comment]
@AllenBird Closing this issue as it seems that you got things sorted out.
