### ISSUE TITLE
Build steps as per read me not building image 

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/base#27]
I followed  instructions to build my own custom image as specified on Read-Me

**## Build**
Add the following to a Dockerfile in the root of your Reaction Commerce project:

`FROM reactioncommerce/base:latest`
Then you can build the image with:

`docker build -t reactioncommerce/reaction:latest .`

**## Issue**
Resultant image is same size as base image.  Looked up docs found nothing.
Can you please direct me to instruction on how to build image using base.
Thanks

**Comment by impactmass** [comment]
Hi @hrath2015, an example of how to build an image using this as base can be found in the Reaction repo here https://github.com/reactioncommerce/reaction/blob/master/Dockerfile

**Comment by hrath2015** [comment]
thanks @impactmass  I  figured it out  to use the dockerfile u suggested.  Sorry delay in update from my side. Closing it now.
