### ISSUE TITLE
Update to directory versioning

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/base#30]
## Update to directory versioning

**Comment by impactmass** [comment]
## Problem: 
For this project to support creating Docker images for different versions of Meteor and other dependencies, the current versioning based on Git tags (and SHA) is limiting.

## Possible Solution(s): 
(A) Versioning based on source files (directories); using a build tool/script that build images from set directories.

## Approach (A)
Taking tips from [Gliderlabs' Alpine docker image](https://github.com/gliderlabs/docker-alpine), restructure repo to look like:

```
├── README.md
└── versions
    ├── meteor-1.7.0.1
    │   ├── Dockerfile
    │   ├── options
    │   └── test-script.sh
    └── meteor-1.7.0.3
        ├── Dockerfile
        ├── options
        └── test-script.sh
```

The `options` file will contain configuration needed to build images from each directory, eg:
```
export TAGS=(v1.7.0.3-meteor latest)
```
The build script goes through all directories with an options file and builds images for all Dockerfiles found.

### [Potential] Issues with Approach (A)
(1) This process _will_ not work alongside our current process of building images for every branch/commit.
(2) With the tags being set from the options file in the source code, the build script can only run on the master branch (to prevent branches overriding an official tagged image). 
(3) We can prefix the tags (either with branch name or Git SHA) while building images on branches, but this would mean pushing a lot of docker images (as the `versions` directory grows)

**Comment by ticean** [comment]
@impactmass :thumbsup: Thanks for the writeup. I think this is the way to go to maintain multiple versions and do proper updating of the tag tree. 

I'm OK if we don't publish every build artifact in this repo as long as everything's tested before a release tag is pushed. This repo is a simpler scenario than our applications. It doesn't need cherry-picking by the team for testing, whereas in reaction we may need to pull `release-1.x.x` or commit `0b87a5` for exhaustive manual tests.

The gliderlabs repo is [building images](https://github.com/gliderlabs/docker-alpine/blob/62606823dbae10f763dae1878f44ec918ac8dce5/.circleci/config.yml#L36) in every triggered run, [testing locally in CI](https://github.com/gliderlabs/docker-alpine/blob/62606823dbae10f763dae1878f44ec918ac8dce5/.circleci/config.yml#L40), but [selectively pushing them](https://github.com/gliderlabs/docker-alpine/blob/62606823dbae10f763dae1878f44ec918ac8dce5/build#L100-L115). The tests in that repo are parallelized using the [CircleCI CLI split](https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-test-files) to reduce the build time.

I think you mentioned something similar in our standup? Always build. Always test. Selective publish releases, from the integration branch (`master`)? Should we ditch our model and use glider's?
