### ISSUE TITLE
mount a volume

### ISSUE THREAD

**Issue by roboto-cloud** [reactioncommerce/base#5]
someone know if possible mount a docker volume for statics files?
what is the path for do it?? and folder owner and permissions...

thanks in advance,

**Comment by jshimko** [comment]
What specifically are you trying to do?  In general, Meteor apps should have static files added to the `/public` or `/private` directories when in development and they will then end up in the right place once the app is built.  Reaction doesn't write anything to the filesystem or save uploaded files to disk (image/file uploads go into the database using MongoDB's gridfs), so I'm not sure what exposing a volume on the app container would accomplish for you.  A Reaction app container is completely stateless.

See the notes on `public` and `private` directories
https://guide.meteor.com/structure.html#special-directories

The `Assets` API for accessing static files in the `private` directory
https://docs.meteor.com/api/assets.html
